# 3.9 thru 3.12 work fine.
# 3.13 can't build the kivy wheel. doesn't SEEM to be a problem?
ARG python_version
FROM python:$python_version

# 0.5.1.Hotfix1 tested
ARG archipelago_tag
RUN git clone --depth 1 --branch $archipelago_tag https://github.com/ArchipelagoMW/Archipelago.git /opt/Archipelago

WORKDIR /opt/Archipelago
RUN find . -name requirements.txt -exec python -m pip install -r '{}' ';'
RUN python -m pip install --upgrade setuptools

# create host.yaml
RUN python -c "import settings; settings.get_settings()"

RUN mkdir -p /data/roms
RUN mkdir -p /data/custom_worlds
RUN mkdir -p /data/Enemizer
RUN mkdir -p /data/SNI
RUN perl -pi -e 's$rom_file: "$rom_file: "/data/roms/$g; s$enemizer_path: "EnemizerCLI/EnemizerCLI.Core"$enemizer_path: "/data/Enemizer/EnemizerCLI.Core"$g; s$sni_path: "SNI"$sni_path: "/data/SNI"$g' host.yaml

EXPOSE 80/tcp

CMD python WebHost.py
