# 3.9 thru 3.12 work fine.
# 3.13 can't build the kivy wheel. doesn't SEEM to be a problem?
ARG python_version
FROM python:$python_version

# 0.6.1 tested
ARG archipelago_tag
RUN git clone --depth 1 --branch $archipelago_tag https://github.com/ArchipelagoMW/Archipelago.git /opt/Archipelago

ARG webhost_port
ARG host_address

WORKDIR /opt/Archipelago
RUN find . -name requirements.txt -exec python -m pip install -r '{}' ';' && \
    python -m pip install --upgrade setuptools

# create host.yaml so we can edit it
RUN python -c "import settings; settings.get_settings()" && \
    perl -pi -e 's$rom_file: "$rom_file: "/data/roms/$g; s$enemizer_path: "EnemizerCLI/EnemizerCLI.Core"$enemizer_path: "/data/externals/EnemizerCLI/EnemizerCLI.Core"$g; s$sni_path: "SNI"$sni_path: "/data/externals/SNI"$g' host.yaml && \
    python -c "import yaml; print(yaml.dump({ 'HOST_ADDRESS': '$host_address', 'PORT': $webhost_port, 'PONY': { 'provider': 'sqlite', 'filename': '/data/db/ap.db3', 'create_db': True } }))" > "/opt/Archipelago/config.yaml"

EXPOSE $webhost_port/tcp
CMD python WebHost.py
