# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
VOLUME /source
WORKDIR /source
RUN dotnet publish -c Release -o /app


# Enable globalization and time zones:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md
# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine
EXPOSE 443/tcp
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./ReverseProxy"]
